sudo: false

language: java
jdk:
  - oraclejdk8

# The tests in this repository intend to fail when `dist` is `trusty`
# (this is the default since the 18th of July). So, we explicitly set `precise`).
# See an URL below for details:
#  - https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default
dist: precise

branches:
  only:
    - master

notifications:
  email: false

install:
  - . ./bin/install-spark.sh
  # Build the SQL server for following unit tests
  - ./build/mvn -q clean package -DskipTests

script:
  # - ENABLE_FAULT_TOLERANCE_TESTS=1 ./build/mvn -q scalastyle:check test
  - ./build/mvn -q scalastyle:check test

after_success:
  - mvn clean
