sudo: false

language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email: false

install:
  - . ./bin/install-spark.sh
  # Build the SQL server for following unit tests
  - ./build/mvn -q clean package -DskipTests

script:
  - ./build/mvn -q scalastyle:check test

after_success:
  - mvn clean
